##
## EPITECH PROJECT, 2020
## makefile
## File description:
## makefile
##

all:
	ln -s ./lib/my_110borwein.py 110borwein
	chmod +x 110borwein

clean:
	rm -f lib/*~

fclean: clean
	rm -f 110borwein

re:	fclean all
